# Generated by Django 4.2.5 on 2023-09-28 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village', models.CharField(max_length=200)),
                ('nombre_de_forêts', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Foret_sacree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_du_responsable', models.CharField(max_length=200)),
                ('superficie_en_hectare', models.DecimalField(decimal_places=2, max_digits=50)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PFE_appli.village')),
            ],
        ),
        migrations.CreateModel(
            name='Foret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_du_propriétaire', models.CharField(max_length=200)),
                ('superficie_en_hectare', models.DecimalField(decimal_places=2, max_digits=50)),
                ('nature_de_la_forêt', models.CharField(max_length=200)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PFE_appli.village')),
            ],
        ),
    ]
